# Generated by Django 4.2.6 on 2023-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_webhook', '0004_alter_webhookevent_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='filters',
            field=models.JSONField(
                blank=True,
                help_text="Filter configuration for models. Format: {'model_name': {'ids': [1, 2, 3], 'bucket': 'value'}}",
                null=True,
            ),
        ),
    ]