# Generated by Django 5.1 on 2025-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0005_webhook_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
