# Generated by Django 5.2.2 on 2025-06-09 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0006_alter_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_ ]+$",
                        message="Webhook name must contain only alphanumeric characters, underscores, or spaces.",
                    )
                ],
            ),
        ),
    ]
