# Generated by Django 5.2.2 on 2025-06-09 11:57

import django.core.validators
from django.db import migrations, models


def update_display_names(apps, schema_editor):
    WebhookTopic = apps.get_model('django_webhook', 'WebhookTopic')
    for topic in WebhookTopic.objects.all():
        if topic.name:
            parts = topic.name.split('/')
            if len(parts) == 2:
                model_part, action_part = parts
                # Extract the model name (after the dot)
                if '.' in model_part:
                    model_name = model_part.split('.')[1]
                    # Capitalize the first letter of the action part
                    action_name = action_part.capitalize()
                    topic.display_name = f"{model_name} {action_name}"
                    topic.save()


class Migration(migrations.Migration):

    dependencies = [
        ("django_webhook", "0007_webhook_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhooktopic",
            name="display_name",
            field=models.CharField(blank=True, editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_ ]+$",
                        message="Webhook name must contain only alphanumeric characters, underscores, or spaces.",
                    )
                ],
            ),
        ),
        migrations.RunPython(update_display_names),
    ]
